server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: 120.48.65.170:8848
        namespace: f46bbdaa-f11e-414f-9530-e6a18cbf91f6
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp18jv9aon3b25431xo.mysql.rds.aliyuncs.com:3306/seata_account
    username: wh
    password: wanghong
seata:
  enabled: true
  application-id: ${spring.application.name}
  # 事务群组（可以每个应用独立取名，也可以使用相同的名字），要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
  tx-service-group: seata-order-service
  config:
    type: nacos
    # 需要和server在同一个注册中心下
    nacos:
      namespace: f46bbdaa-f11e-414f-9530-e6a18cbf91f6
      serverAddr: 120.48.65.170:8848
      # 需要server端(registry和config)、nacos配置client端(registry和config)保持一致
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      # 需要和server端保持一致，即server在nacos中的名称，默认为seata-server
      application: seata-server
      server-addr: 120.48.65.170:8848
      group: SEATA_GROUP
      namespace: f46bbdaa-f11e-414f-9530-e6a18cbf91f6
      username: "nacos"
      password: "nacos"

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml


